### ISSUE TITLE
Consider contributor covenant

### ISSUE THREAD

**Issue by chadaustin** [cruxlang/crux#105]
http://contributor-covenant.org/version/1/3/0/

**Comment by andyfriesen** [comment]
:+1:

What do we have to do?

**Comment by chadaustin** [comment]
I'm not precisely sure, but I think one of us just needs to see where we
need to put the file in the repo.

On Mon, Jun 6, 2016 at 1:46 PM, Andy Friesen <notifications@github.com>
wrote:

> 👍
>
> What do we have to do?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cruxlang/crux/issues/105#issuecomment-224082896>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AADqU5fOTYK1ThEJEb35lzvlFu6_cTbRks5qJIcpgaJpZM4IvJVH>
> .
>



-- 
Chad Austin
http://chadaustin.me

**Comment by chadaustin** [comment]
@Xena argued it attracts drama and isn't necessary.  I did some googling around on the contributor covenant and there are lots of gamergate "discussions" and witch hunts.  Weee.  I think the answer is -- let's punt on this until we have a bigger community.
