### ISSUE TITLE
Optional Record Properties

### ISSUE THREAD

**Issue by andyfriesen** [cruxlang/crux#176]
# Motivating Case

Part of being a delightful, practical tool is readily supporting popular third-party libraries.  Facebook's React is as popular as it gets.

Crux must be a great way to write React programs.

# Types

This is actually the easiest part.  If a function argument is a record, and a field has type `js.option.JSOption<a>`, that field can be omitted by callers.

A simple example:
```
import js.option

fun printMyRecord<T: {required: Number, optional: option.JSOption<String>}>(r: T) {
    print(r.required)
    r.optional->maybe(fun(s) {
        print(s)
    }, ())
    print("-")
}
```

Both of the following are valid ways to call this function
```
import js.option

printMyRecord({required: 1})
printMyRecord({required: 2, optional: option.some("present")})
```

**Comment by chadaustin** [comment]
I love that this turned out to be so easy.
