### ISSUE TITLE
What is meant by "Sums" in the README?

### ISSUE THREAD

**Issue by enricozb** [cruxlang/crux#190]
Does it mean that Crux supports Sum/Union types? If so are they tagged or untagged unions, and is there and could I see a code sample of this?

**Comment by andyfriesen** [comment]
Crux sum types are tagged unions like you see in Rust, OCaml, and Haskell.

Here's a simple example, from our test suite: https://github.com/cruxlang/crux/blob/9736ca5594bd9ed59ffcc5e10fb3bf3adac804f0/tests/integration/datatypes/main.cx

**Comment by enricozb** [comment]
Just what I needed. Thanks!
