### ISSUE TITLE
structure for compiler errors

### ISSUE THREAD

**Issue by chadaustin** [cruxlang/crux#27]
We have a lot of `Either String`.  We ought to instead introduce some kind of structured `Error` type and use that instead.

**Comment by andyfriesen** [comment]
I did most of this by accident but it's not used everywhere yet.

https://github.com/andyfriesen/crux/blob/master/Crux/Typecheck/Types.hs#L30

**Comment by chadaustin** [comment]
Nice!

**Comment by chadaustin** [comment]
done
