### ISSUE TITLE
allow lowercase types, uppercase vars

### ISSUE THREAD

**Issue by chadaustin** [cruxlang/crux#31]
This means we'll need to use symbol tables instead of case to disambiguate types vs. type variables and values vs. constructors.

Also introduce the idea of "value position" and "type position", which TypeScript does and seems to work well.

OPEN QUESTION: how does pattern matching work.  are we okay with sacrificing accidental passthru.  do good compiler warnings solve this problem?

**Comment by chadaustin** [comment]
This may imply lowercase module names are worthwhile.  The module names in Go and TypeScript feel good, and there's no good reason not to support lowercase, so we should probably just do that.

**Comment by chadaustin** [comment]
Actually, I now have a driving example for lowercase module names: json.  JSON is too much caps, and Json is ugly.  Ideally, programmnig languages would use the same notation that people use everywhere else, when it's practical.  So "json" is probably the best name of the module.  This matches Python.

(I understand this is entirely a taste thing.  We should run a survey for these kinds of taste things.)

**Comment by chadaustin** [comment]
Bizarrely, Java has both conventions XML and Json.  .NET uses Xml and Json by convention.

**Comment by chadaustin** [comment]
After talking to some folks in #nachos about this, I think it would be wrong to have a convention based on whether a word is an acronym or not, because that is fuzzy over time.  Acronyms become words and vice versa.  I think the names of the modules/types/values should match how people start, say, sentences with them.  If you started an English sentence with Abcde instead of ABCDE (like Email) then it should be spelled that way in code.  If you started an English sentence with ABCDE (like JSON or XML) then it should be capitalized in code (or lowercased, depending on context).

**Comment by andyfriesen** [comment]
OCaml requires types and bindings to both be lowercase.  What does it do?

**Comment by chadaustin** [comment]
done
