### ISSUE TITLE
rethink generics

### ISSUE THREAD

**Issue by chadaustin** [cruxlang/crux#32]
Solve for the following features:

1. Explicit vs. implicit introduction of type variables, unless inferred for functions (never inferred for data types) (ScopedTypeVariables is a requirement -- type variables should have scopes just like values do)
2. Use the same "type application" syntax for functions and data types.
3. Reasonable, familiar syntax for both generic functions under function sugar w/ annotations and in desugared type annotations for functions.
4. RankNTypes
5. Application of type families??

**Comment by andyfriesen** [comment]
Strawman:

```
forall { a, b }
fun map(f : (a) -> b, l -> Array b) -> Array b { ... }
```

`forall` introduces a type variable, scoped to the following declaration.

This syntax admits two things at once.  The first is a name for a record type.

```
forall { a : {mutable x: Number, y: mutable Number, ... }
fun transpose(point : a) : a { ... }
```

Here, we constrain the type `a` to be a particular record including fields `x` and `y`, then use that name to describe a function that takes a record, and returns a record of the exact same type.

Secondly, this elegantly admits describing traits and other constraints we might want to place on types.

```
forall { a <= Ordered } // could also be a : Ordered, I think.
fun ...
```

**Comment by chadaustin** [comment]
done
