### ISSUE TITLE
RFC: import syntax

### ISSUE THREAD

**Issue by Xe** [cruxlang/crux#5]
As module support becomes needed, we should hammer down the logic behind importing other modules before it becomes too late. This is a request for comment (RFC).

I suggest that the following keywords be added to the sneak AST such that:

`import` => Imports a module by the following rules

`locally` => qualifies an import by adding the module specified into that module's scope as an unqualified global

`as` => qualifies an import by naming the qualifier

## Import Rules

Let `XeServ.Foo` be a module containing members `bar`, `baz` and `Hoober`.

| Statement | Effect |
|:--- |:--- |
| `import XeServ.Foo` | All members of `XeServ.Foo` are qualified by `XeServ.Foo` |
| `import XeServ.Foo as Foo` | All members of `XeServ.Foo` are qualified by `Foo` | 
| `import XeServ.Foo locally` | All members of `XeServ.Foo` are imported unqualified |
| `import XeServ.Foo (bar, baz)` | `bar` and `baz` are qualified as `XeServ.Foo.bar` and `XeServ.Foo.baz` |
| `import XeServ.Foo locally (bar, baz)` | `bar` and `baz` are imported unqualified |
| `import XeServ.Foo locally as Bar` | Syntax error |
| `import XeServ.Foo locally (bar) as somethingElse` | Syntax error |

**Comment by chadaustin** [comment]
`import A.B as B` duplicates which is something I'd like to avoid.

**Comment by chadaustin** [comment]
BTW, the constraints of any proposed syntax are:

- no duplication in import list
- optimize for the most common import form: `import qualified A.B as B` in Haskell
- next, optimize for the second-most common import form: `import A.B` in Haskell.  `from A.B import *` in Python.

**Comment by andyfriesen** [comment]
Strawman: Let's just do exactly what Python does.

```python
import A.B.C
from A.B.C import D, E, F
from A.B.C import *
```

**Comment by chadaustin** [comment]
@andyfriesen mentions another possibility which is always supporting fully-qualified names without requiring explicit imports.  That is, you could call A.B.foo from anywhere.  This has pretty nice convenience properties as a programmer, but makes parsing and type checking a bit harder.

**Comment by chadaustin** [comment]
this is done
