### ISSUE TITLE
RFC: module naming

### ISSUE THREAD

**Issue by Xe** [cruxlang/crux#6]
Modules in Sneak should be implemented such that a module name:

1. Consists of an organization name and a specific name.
2. Is unique across your Sneak code
3. Correlates to the path of the Sneak source code on the disk relative to the project root

There may be any number of additional qualifying names after an initial specific name, such as `XeServ.Foo.Bar` or `XeServ.Database.Redis`. Files should be arranged on the disk such that:

`XeServ.Database.Redis` `->` `src/XeServ/Database/Redis.sk`

An example valid module name would be `XeServ.Foo` where `Foo` is the specific name and `XeServ` is the organization name. An example invalid module name would be `Network.Foo` where `Network` is too vague of an organization name.

All standard library code will have the organizational name `Sneak`.

**Comment by Xe** [comment]
Updated the RFC body to account for Crux -> Sneak.

**Comment by chadaustin** [comment]
this is done
